### ISSUE TITLE
deleteアイコン上に透明でクリックできない部分がある

### ISSUE THREAD

**Issue by rooa** [sosuke-k/paper-tree-client#9]
### 概要

おそらく年号のcontentがアイテム幅と同じくいっぱいにあるため、それとかぶるdeleteアイコン部分はクリックできない状況。

**Comment by sosuke-k** [comment]
https://github.com/sosuke-k/paper-tree-client/blob/master/src/custom_components/link-card.html#L47
`paper-icon-button` の位置を変更？

**Comment by sosuke-k** [comment]
https://github.com/sosuke-k/paper-tree-client/pull/10
